export { default as StartScreen } from './StartScreen'
export { default as LoginScreen } from './LoginScreen'
export { default as RegisterScreen } from './RegisterScreen'
export { default as ResetPasswordScreen } from './ResetPasswordScreen'
export { default as Dashboard } from './Dashboard'
export { default as AboutUs } from './AboutUs'
export { default as ContactUs } from './ContactUs'
export { default as Location } from './Location'
export { default as OurBrochure } from './OurBrochure'
export { default as Home } from './Home'
export { default as Inbox } from './Inbox'
export { default as Payments } from './Payments'
export { default as Profile } from './Profile'
export { default as Transactions } from './Transactions'
export { default as BroucherDetail } from './BroucherDetail'
export { default as Courses } from './Courses'
export { default as Consultanc } from './Consultanc'
export { default as OfferAndPackage } from './OfferAndPackage'



